apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
nameSuffix: -v1

resources:
  - ../../base

replicas:
  - name: nginx-deployment
    count: 3

images:
  - name: nginx
    newName: nginx
    newTag: 1.21.0

patchesStrategicMerge:
  - service-patch.yaml
