apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chart-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/autsu/argocd-lab.git
    targetRevision: HEAD
    path: helm/nginx # 指向Helm Chart目录
    helm:
      valueFiles:
        - values.yaml
      # 可以覆盖values中的值
      values: |
        replicaCount: 2
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
