apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-repo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami # Helm仓库URL
    targetRevision: 9.8.0 # Chart版本
    chart: nginx # Chart名称
    helm:
      values: |
        replicaCount: 3
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
